cargo-features = ["strip"]

[workspace]
members = ["packages/*"]

[patch.crates-io]
# Use our fork of oxipng that removes a dependency and an unneeded sanity check
oxipng = { git = "https://github.com/ComunidadAylas/oxipng", branch = "packsquash" }
# Use our fork of glsl that allows it to parse files that use DOS-style CRLF line
# endings, prevalent on Windows environments, fixes the #elif preprocessor directive
# not being parsed, improves minification and fixes some incorrect transpiling
# Related PRs:
# https://github.com/phaazon/glsl/pull/138
# https://github.com/ComunidadAylas/glsl/pull/1
glsl = { git = "https://github.com/ComunidadAylas/glsl", branch = "packsquash" }
# Use our fork of Zopfli that includes streaming support and the ability to change
# the number of compression iterations
zopfli = { git = "https://github.com/ComunidadAylas/zopfli", branch = "packsquash" }
# imagequant supposedly released a new version with a fix for a critical off-by-one error
# that we've submitted, but it looks like it didn't make it. Compare the following:
# https://docs.rs/imagequant/4.0.0-beta.9/src/imagequant/remap.rs.html#35
# https://github.com/ImageOptim/libimagequant/blob/b6171712c95b9e79e551323b14ea861f4187bf73/src/remap.rs#L35
# Therefore, patch it until a release is made with the fix
imagequant = { git = "https://github.com/ImageOptim/libimagequant", rev = "01681360" }

# Use a newer commit of the csv crate, that's pulled in by development dependencies
# for benchmarking, that depends on a itoa version consistent with the rest of the
# crates ecosystem. Related PR: https://github.com/BurntSushi/rust-csv/pull/255
csv = { git = "https://github.com/BurntSushi/rust-csv", rev = "41c71ed3" }
# Use our fork of mmap, pulled by development dependencies for benchmarking, to fix its
# dependency on unmaintained crates and reduce duplicate dependency versions. Some of
# the changes were authored by jbreitbart.
# Related PR: https://github.com/rbranson/rust-mmap/pull/13
mmap = { git = "https://github.com/ComunidadAylas/rust-mmap" }
# Use our fork of perfcnt that reduces incompatible dependencies versions
perfcnt = { git = "https://github.com/ComunidadAylas/rust-perfcnt" }
# Use our fork of the system-deps build dependency that reduces incompatible dependencies
# versions
system-deps = { git = "https://github.com/ComunidadAylas/system-deps" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.bench]
inherits = "release"
debug = true
strip = "none"
