cargo-features = ["strip"]

[workspace]
members = ["packages/*"]

[patch.crates-io]
# Use our fork of oxipng that removes a dependency and an unneeded sanity check
oxipng = { git = "https://github.com/ComunidadAylas/oxipng", branch = "packsquash" }
# Use our fork of glsl that allows it to parse files that use DOS-style CRLF line
# endings, prevalent on Windows environments, fixes the #elif preprocessor directive
# not being parsed, improves minification and fixes some incorrect transpiling
# Related PRs:
# https://github.com/phaazon/glsl/pull/138
# https://github.com/ComunidadAylas/glsl/pull/1
glsl = { git = "https://github.com/ComunidadAylas/glsl", branch = "packsquash" }
# Use our fork of Zopfli that includes streaming support and the ability to change
# the number of compression iterations
zopfli = { git = "https://github.com/ComunidadAylas/zopfli", branch = "packsquash" }
# Use the latest commits of imagequant that fix an off-by-one error that prevents quantization
imagequant = { git = "https://github.com/ImageOptim/libimagequant" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.debug-release]
inherits = "release"
debug = true
strip = "none"
