[package]
name = "packsquash"
description = "Minecraft resource pack optimizer"
version = "0.3.0"
authors = ["Alejandro \"AlexTMjugador\" González"]
repository = "https://github.com/ComunidadAylas/PackSquash"
license = "AGPL-3.0"
publish = false
edition = "2018"
resolver = "2"

[dependencies]
globset = "0.4.6"
enumset = { version = "1.0.6", features = ["serde"] }
bytes = "1.0.1"
indexmap = { version = "1.6.2", default-features = false, features = ["serde-1"] }
thiserror = "1.0.24"

tokio = { version = "1.4.0", default-features = false, features = ["rt-multi-thread", "macros", "parking_lot"] }
tokio-util = { version = "0.6.5", default-features = false, features = ["codec", "io"] }
tokio-stream = { version = "0.1.5", default-features = false }
futures = { version = "0.3.13", default-features = false }

getopts = "0.2.21"
num_cpus = "1.13.0"

serde = { version = "1.0.125", features = ["derive"] }
toml = "0.5.8"

serde_json = "1.0.64"
json_comments = "0.2.0"
jsonpath_lib = "0.2.6"

spng = { version = "0.1.0", default-features = false, features = ["zlib-ng"] }
png = "0.16.8"
rgb = "0.8.27"
imagequant = "3.0.4-alpha.2"
oxipng = { version = "4.0.3", default-features = false, features = ["zopfli"] }

gstreamer = { version = "0.16.7", default-features = false }
gstreamer-app = { version = "0.16.5", default-features = false, features = ["v1_10"] }

glsl = "6.0.0"

java-properties = { version = "1.3.0", optional = true }

crc32fast = "1.2.1"
zopfli = "0.4.0"

[patch.crates-io]
# Use our fork of oxipng that makes cloudflare-zlib optional.
# This allows fixing Windows builds with MinGW.
# See: https://gitlab.com/kornelski/cloudflare-zlib-sys/-/issues/1
# https://github.com/shssoichiro/oxipng/pull/369
# It also removes a dependency and an unneeded sanity check
oxipng = { git = "https://github.com/ComunidadAylas/oxipng", branch = "packsquash" }
# Use the latest commit of imagequant, which allows some zero-copy operations
imagequant = { git = "https://github.com/ImageOptim/libimagequant" }
# Use a third-party fork of glsl that allows it to parse files that use
# DOS-style CRLF line endings, prevalent on Windows environments.
# See: https://github.com/phaazon/glsl/pull/138
glsl = { git = "https://github.com/vtavernier/glsl", branch = "fix/dos-crlf" }

[build-dependencies]
vergen = { version = "5.1.0", default-features = false, features = ["cargo", "git"] }
time = "0.2.26"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[dev-dependencies]
tokio-test = "0.4.1"

[features]
# Support all kinds of files added by modifications by default
default = ["mod-support"]
# This feature will include support for all the mods that PackSquash will ever support
mod-support = ["optifine-support"]

optifine-support = ["java-properties"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
