[package]
name = "packsquash"
description = "Minecraft resource pack optimizer"
version = "0.3.0"
authors = ["Alejandro \"AlexTMjugador\" González"]
repository = "https://github.com/ComunidadAylas/PackSquash"
license = "AGPL-3.0"
publish = false
edition = "2018"
resolver = "2"

[dependencies]
lazy_static = "1.4.0"
getopts = "0.2.21"
simple-error = "0.2.3"
num_cpus = "1.13.0"
rusty_pool = { version = "0.5.0", default-features = false }
tempfile = "3.2.0"
enumset = { version = "1.0.3", features = ["serde"] }
serde = { version = "1.0.123", features = ["derive"] }
toml = "0.5.8"
globset = "0.4.6"
indexmap = { version = "1.6.1", default-features = false, features = ["serde-1"] }
serde_json = "1.0.61"
json_comments = "0.2.0"
lodepng = "3.4.3"
rgb = "0.8.25"
imagequant = "3.0.3"
gstreamer = "0.16.5"
gstreamer-app = "0.16.5"
gstreamer-audio = "0.16.5"
crc32fast = "1.2.1"
zopfli = "0.4.0"
java-properties = "1.3.0"
glsl = "6.0.0"
sysinfo = { version = "0.16.0", default-features = false }
# Work around funty and bitvec havoc
# See: https://github.com/myrrlyn/funty/issues/3
funty = "=1.1.0"

# Use our fork of oxipng that makes cloudflare-zlib optional.
# This allows fixing Windows builds with MinGW.
# See: https://gitlab.com/kornelski/cloudflare-zlib-sys/-/issues/1
[patch.crates-io.oxipng]
git = 'https://github.com/ComunidadAylas/oxipng'

# We depend on OxiPNG with cloudflare-zlib for Unix x64 and Aarch64 platforms
[target.'cfg(all(unix, any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
oxipng = { version = "4.0.3", default-features = false, features = ["zopfli", "cloudflare-zlib"] }

# For Windows or non x64/Aarch64 platforms, we don't use cloudflare-zlib
[target.'cfg(any(windows, not(any(target_arch = "x86_64", target_arch = "aarch64"))))'.dependencies]
oxipng = { version = "4.0.3", default-features = false, features = ["zopfli"] }

[build-dependencies]
vergen = "3.1.0"
time = "0.2.25"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
