cargo-features = ["strip"]

[package]
name = "packsquash"
description = "Minecraft resource and data pack optimizer"
version = "0.3.0"
authors = ["Alejandro \"AlexTMjugador\" González"]
repository = "https://github.com/ComunidadAylas/PackSquash"
license = "AGPL-3.0"
readme = "README.md"
publish = false
edition = "2018"

[dependencies]
bytes = "1.0.1"
globset = "0.4.8"
enumset = { version = "1.0.7", features = ["serde"] }
indexmap = { version = "1.7.0", default-features = false, features = ["serde-1"] }
thiserror = "1.0.26"
ahash = "0.7.4"

num_cpus = "1.13.0"
sysinfo = { version = "0.19.2", default-features = false }
walkdir = "2.3.2"

tokio = { version = "1.9.0", default-features = false, features = ["rt-multi-thread", "macros", "io-util", "fs", "sync"] }
tokio-util = { version = "0.6.7", default-features = false, features = ["codec", "io"] }
tokio-stream = { version = "0.1.7", default-features = false }
futures = { version = "0.3.16", default-features = false }

getopts = "0.2.21"

serde = { version = "1.0.127", features = ["derive"] }
toml = "0.5.8"

serde_json = "1.0.66"
json_comments = "0.2.0"
jsonpath_lib = "0.3.0"

spng = { version = "0.1.0", default-features = false }
png = "0.16.8"
rgb = "0.8.27"
imagequant = "3.0.4-alpha.2"
oxipng = { version = "5.0.0", default-features = false, features = ["zopfli"] }

gstreamer = { version = "0.17.1", default-features = false }
gstreamer-app = { version = "0.17.0", default-features = false, features = ["v1_10"] }

glsl = "6.0.1"

java-properties = { version = "1.4.0", optional = true }

tempfile = "3.2.0"
crc32fast = "1.2.1"
zopfli = "0.4.0"

const-random = "0.1.13"
aes = "0.7.4"
fpe = "0.5.0"
uuid = "0.8.2"
entropy = "0.4.1"
rand_xoshiro = "0.6.0"

color-backtrace = { version = "0.5.1", default-features = false, optional = true }

[target.'cfg(windows)'.dependencies]
winreg = "0.9.0"
wmi = "0.9.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.1"
mach = "0.3.2"

[patch.crates-io]
# Use our fork of oxipng that removes a dependency and an unneeded sanity check
oxipng = { git = "https://github.com/ComunidadAylas/oxipng", branch = "packsquash" }
# Use the latest commit of imagequant, which allows some zero-copy operations
imagequant = { git = "https://github.com/ImageOptim/libimagequant" }
# Use our fork of glsl that allows it to parse files that use DOS-style CRLF line
# endings, prevalent on Windows environments, and fixes the #elif preprocessor
# directive not being parsed
# See: https://github.com/phaazon/glsl/pull/138
glsl = { git = "https://github.com/ComunidadAylas/glsl", branch = "packsquash" }
# Use our fork of Zopfli that includes streaming support and the ability to change
# the number of compression iterations
zopfli = { git = "https://github.com/ComunidadAylas/zopfli", branch = "packsquash" }

[build-dependencies]
vergen = { version = "5.1.14", default-features = false, features = ["cargo", "git"] }
time = { version = "0.3.0", default-features = false, features = ["std"] }

[dev-dependencies]
tokio-test = "0.4.2"

[features]
# Support all kinds of files added by modifications and fancy panic messages by default
default = ["mod-support", "color-backtrace"]
# This feature will include support for all the mods that PackSquash will ever support
mod-support = ["optifine-support"]

optifine-support = ["java-properties"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[package.metadata.deb]
maintainer = "Alejandro González <AlexTMjugador@users.noreply.github.com>"
copyright = "PackSquash developers"
license-file = ["LICENSE", "0"]
extended-description-file = "target/debian/extended_package_description.txt"
section = "utils"
# Sadly, automatic dependency detection is suboptimal because it pulls transitive
# dependencies and does not work fine when cross-compiling. The value for this depends
# key is manually deduced as follows:
# - $auto is used, preferably on a CI runner, to get all the relevant dependencies and
#   their versions.
# - The list is then manually tweaked to eliminate transitive dependencies.
# This process must be repeated:
# - Each time a CI runner is updated in a way that may change these versions (distro
#   update; libc is especially important to get right).
# - Before each release in the APT repository, just in case, to check that everything's
#   right
depends = "gstreamer1.0-plugins-bad (>=1.14.5), gstreamer1.0-plugins-base (>=1.14.5), gstreamer1.0-plugins-good (>=1.14.5), libc6 (>= 2.27)"
