[package]
name = "packsquash"
version = "0.1.2"
authors = ["AlexTMjugador"]
edition = "2018"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[dependencies]
lazy_static = "1.4.0"
clap = "2.33.3"
simple-error = "0.2.2"
num_cpus = "1.13.0"
threadpool = "1.8.1"
tempfile = "3.1.0"
serde_json = "1.0.59"
lodepng = "3.2.2"
rgb = "0.8.25"
imagequant = "2.12.5"
oxipng = "3.0.1"
gstreamer = "0.16.4"
gstreamer-app = "0.16.3"
crc32fast = "1.2.0"
zopfli = "0.4.0"
java-properties = "1.2.0"
