[package]
name = "packsquash"
description = "Lossily compresses and prepares Minecraft resource packs for distribution"
version = "0.2.1"
authors = ["Alejandro \"AlexTMjugador\" González"]
repository = "https://github.com/ComunidadAylas/PackSquash"
license = "AGPL-3.0"
publish = false
edition = "2018"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[dependencies]
lazy_static = "1.4.0"
getopts = "0.2.21"
simple-error = "0.2.2"
num_cpus = "1.13.0"
rusty_pool = { version = "0.4.3", default-features = false }
tempfile = "3.1.0"
enumset = { version = "1.0.1", features = ["serde"] }
serde = { version = "1.0.116", features = ["derive"] }
toml = "0.5.7"
globset = "0.4.5"
indexmap = { version = "1.6.0", default-features = false, features = ["serde-1"] }
serde_json = "1.0.59"
json_comments = "0.2.0"
lodepng = "3.2.2"
rgb = "0.8.25"
imagequant = "2.12.5"
#oxipng = { version = "3.0.1", default-features = false }
gstreamer = "0.16.4"
gstreamer-app = "0.16.3"
crc32fast = "1.2.0"
zopfli = "0.4.0"
java-properties = "1.2.0"
glsl = "5.0.1"

[build-dependencies]
vergen = "3.1.0"
time = "0.2.22"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
