[workspace]
members = ["packages/*"]
resolver = "2"

[patch.crates-io]
# Use our fork of glsl-lang that allows it to parse #moj_import directives
glsl-lang = { git = "https://github.com/ComunidadAylas/glsl-lang" }
glsl-lang-lexer = { git = "https://github.com/ComunidadAylas/glsl-lang" }
glsl-lang-pp = { git = "https://github.com/ComunidadAylas/glsl-lang" }
glsl-lang-types = { git = "https://github.com/ComunidadAylas/glsl-lang" }

# Use our fork of mmap, pulled by development dependencies for benchmarking, to fix its
# dependency on unmaintained crates and reduce duplicate dependency versions. Some of
# the changes were authored by jbreitbart.
# Related PR: https://github.com/rbranson/rust-mmap/pull/13
mmap = { git = "https://github.com/ComunidadAylas/rust-mmap" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.bench]
inherits = "release"
debug = true
strip = "none"
