[workspace]
members = ["packages/*"]

[patch.crates-io]
# Use our fork of oxipng that removes a dependency and an unneeded sanity check
oxipng = { git = "https://github.com/ComunidadAylas/oxipng", branch = "master" }
# Use our fork of glsl that allows it to parse files that use DOS-style CRLF line
# endings, prevalent on Windows environments, fixes the #elif preprocessor directive
# not being parsed, improves minification and fixes some incorrect transpiling
# Related PRs:
# https://github.com/phaazon/glsl/pull/138
# https://github.com/ComunidadAylas/glsl/pull/1
# https://github.com/ComunidadAylas/glsl/pull/2
glsl = { git = "https://github.com/ComunidadAylas/glsl", branch = "packsquash" }

# Use a newer commit of the csv crate, that's pulled in by development dependencies
# for benchmarking, that depends on a itoa version consistent with the rest of the
# crates ecosystem. Related PR: https://github.com/BurntSushi/rust-csv/pull/255
csv = { git = "https://github.com/BurntSushi/rust-csv", rev = "41c71ed3" }
# Use our fork of mmap, pulled by development dependencies for benchmarking, to fix its
# dependency on unmaintained crates and reduce duplicate dependency versions. Some of
# the changes were authored by jbreitbart.
# Related PR: https://github.com/rbranson/rust-mmap/pull/13
mmap = { git = "https://github.com/ComunidadAylas/rust-mmap" }
# Use a newer commit of the backtrace crate, that's pulled in as a transitive dependency
# for color-backtrace, that depends on a miniz_oxide version consistent with the rest
# of the crates ecosystem. Related PR: https://github.com/rust-lang/backtrace-rs/pull/463
backtrace = { git = "https://github.com/rust-lang/backtrace-rs", rev = "38cb2d55" }
# Use a patch of the serde_derive crate with PR #1544 merged, which greatly improves error
# messages when deserializing data, including options files.
# See: https://github.com/serde-rs/serde/pull/1544
serde_derive = { git = "https://github.com/ComunidadAylas/serde", branch = "master" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.bench]
inherits = "release"
debug = true
strip = "none"
