# Configuration file format reference:
# https://embarkstudios.github.io/cargo-deny/checks/index.html

targets = [
	{ triple = "x86_64-unknown-linux-gnu" },
	{ triple = "aarch64-unknown-linux-gnu" },
	{ triple = "x86_64-pc-windows-gnu" },
	{ triple = "x86_64-apple-darwin" }
]

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
ignore = [
	# chrono depends on a version of time with another security advisory.
	# chrono is a direct transitive dependency we use for building. In
	# Windows builds it also is used at runtime by the wmi crate
	"RUSTSEC-2020-0159",
	# This old version of time pulled by chrono might dereference a null
	# pointer in Unix platforms. But this is not a concern at build time,
	# and Windows builds (which actually use this library at runtime) are
	# not affected
	"RUSTSEC-2020-0071",
	# Criterion depends on serde_cbor, which is unmaintained and has some quirks, but works:
	# https://github.com/pyfisch/cbor/issues/179
	"RUSTSEC-2021-0127"
]

[licenses]
unlicensed = "deny"
allow = [
	# Free software licenses compatible with (A)GPL.
	# List extracted from: https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses
	"GPL-3.0",
	"GPL-2.0",
	"LGPL-3.0",
	"LGPL-2.1",
	"AGPL-3.0",
	"FSFAP",
	"Apache-2.0",
	"Artistic-2.0",
	"ClArtistic",
	"Sleepycat",
	"BSL-1.0",
	"BSD-3-Clause",
	"CECILL-2.0",
	"BSD-3-Clause-Clear",
	"ECL-2.0",
	"EFL-2.0",
	"EUDatagrid",
	"MIT",
	"BSD-2-Clause",
	"FTL",
	"HPND",
	"iMatix",
	"Imlib2",
	"IJG",
	"Intel",
	"ISC",
	"MPL-2.0",
	"NCSA",
	"OLDAP-2.7",
	"NIST-PD",
	"CC-PDDC",
	"CC0-1.0",
	"Python-2.0",
	"Ruby",
	"SGI-B-2.0",
	"SMLNJ",
	"UPL-1.0",
	"Unlicense",
	"Vim",
	"W3C",
	"WTFPL",
	"X11",
	"XFree86-1.1",
	"Zlib",
	"zlib-acknowledgement",
	"ZPL-2.0",
	"ZPL-2.1",
	# Not expressely listed as (A)GPL compatible in the page above, but
	# according to https://opensource.org/licenses/0BSD it is a modification
	# of the ISC license, which is compatible. Its text is also extremely
	# simple and allows using the code for any purpose
	"0BSD"
]
default = "deny"
copyleft = "allow"
unused-allowed-license = "allow"

[licenses.private]
ignore = true

# This section is considered when running `cargo deny check bans`.
# More documentation about the 'bans' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
skip = [
	# chrono depends on this old version of the time crate
	{ name = "time", version = "=0.1.43" }
]
skip-tree = [
	# An ancient nom is pulled by the development dependency for
	# benchmarking perfcnt. Let's ignore that for now. It doesn't
	# affect the final user executables at all
	{ name = "perfcnt", version = "=0.7.3" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = ["https://github.com/ImageOptim/libimagequant", "https://github.com/BurntSushi/rust-csv"]

[sources.allow-org]
github = ["ComunidadAylas"]
