# Cargo configuration file for PackSquash.
# Reference: https://doc.rust-lang.org/cargo/reference/config.html
# This file is primarily useful for specifying custom rustflags

# Generate code for the x64 microarchitecture level 2 for x64 targets.
# This is broadly compatible (virtually any CPU manufactured after
# 2009 is compatible) and provides some nice speedups. CPUs that
# don't support it probably are too slow for PackSquash anyway. See:
# https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels
[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=x86-64-v2"]

[target.'cfg(all(target_os = "linux", target_arch = "aarch64"))']
runner = 'qemu-aarch64'

[target.aarch64-unknown-linux-gnu]
linker = 'aarch64-linux-gnu-gcc'

[target.aarch64-unknown-linux-musl]
linker = 'aarch64-linux-musl-gcc'
# Statically link with gcc to provide long double builtins required on Aarch64
# but not reliably provided by the Rust toolchain.
# See: https://github.com/rust-lang/rust/issues/46651#issuecomment-641172562
rustflags = ["-C", "link-arg=-lgcc"]
