name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always
  DEBIAN_FRONTEND: noninteractive

  CONST_RANDOM_SEED: ${{ secrets.CONST_RANDOM_SEED }}
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  static-analysis:

    runs-on: ubuntu-latest

    # Only run if this is not a pull request, or for pull requests on forks
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != 'ComunidadAylas/PackSquash'

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@v3

      # Necessary due to Tauri macro expectations. See: https://github.com/tauri-apps/tauri/issues/3142
      - name: 📁 Create GUI package frontend dist directory
        run: mkdir packages/packsquash_gui/dist

      - name: 🧰 Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy

      - name: 🧰 Install development packages
        run: |
          sudo apt-get update
          sudo apt-get install desktop-file-utils libwebkit2gtk-4.0-dev

      - name: 🔍 Check workflow write permission
        id: check_write_permission
        uses: scherermichael-oss/action-has-permission@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔍 Clippy check (with annotations)
        uses: actions-rs/clippy-check@v1
        if: steps.check_write_permission.outputs.has-permission
        with:
          args: --all-targets
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔍 Clippy check (without annotations)
        if: ${{ !steps.check_write_permission.outputs.has-permission }}
        run: cargo clippy --all-targets

      - name: 🔍 ESLint check
        working-directory: packages/packsquash_gui
        run: |
          npm ci
          npm run lint

      - name: 🔍 Cargo deny check
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: 🔍 Check PackSquash Linux desktop entries correctness
        run: bash -ce 'shopt -s globstar; desktop-file-validate **/*.desktop'

      - name: 🔍 Check Rust source code format
        run: cargo fmt --all --check

      - name: 🔍 Check TypeScript source code format
        working-directory: packages/packsquash_gui
        run: npm run format

  build:

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin

        include:
          - target: x86_64-unknown-linux-gnu
            host-target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            container: debian:bullseye-slim
            pkg-config-path: /usr/lib/x86_64-linux-gnu/pkgconfig
            apt-arch: amd64
            appimage-arch: x86_64

          - target: x86_64-pc-windows-msvc
            host-target: x86_64-pc-windows-msvc
            runner: windows-latest
            cli-executable: packsquash_cli.exe

          - target: aarch64-unknown-linux-gnu
            host-target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            container: debian:bullseye-slim
            pkg-config-path: /usr/lib/aarch64-linux-gnu/pkgconfig
            apt-arch: arm64
            appimage-arch: aarch64

          - target: x86_64-apple-darwin
            host-target: x86_64-apple-darwin
            runner: macos-latest
            cli-executable: packsquash_cli

          - target: aarch64-apple-darwin
            host-target: x86_64-apple-darwin
            runner: macos-latest
            cli-executable: packsquash_cli

    runs-on: ${{ matrix.runner }}

    container: ${{ matrix.container }}

    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
      TARGET_APPIMAGE_ARCH: ${{ matrix.appimage-arch }}
      TARGET_APPIMAGE_APT_ARCH: ${{ matrix.apt-arch }}
      PKG_CONFIG_ALLOW_CROSS: 1
      PKG_CONFIG_PATH: ${{ matrix.pkg-config-path }}

    # Only run if this is not a pull request, or for pull requests on forks
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != 'ComunidadAylas/PackSquash'

    steps:
      - name: 📦 Add Linux ARM64 architecture APT packages
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          dpkg --add-architecture arm64
          apt-get update

      - name: 🧰 Install toolchain
        if: matrix.runner == 'ubuntu-latest'
        run: |
          apt-get update
          # curl is required by rustup and Tauri.
          # markdown and html2text are required to generate the Debian package only.
          # The third line contains packages necessary for appimage-builder only.
          # The fourth line contains packages necessary for Tauri.
          # The fifth line contains packages necessary for build-time JSON Schema generation
          apt-get install -yq build-essential git curl \
                              markdown html2text \
                              python3-venv file zsync desktop-file-utils gtk-update-icon-cache fakeroot squashfs-tools gstreamer1.0-tools \
                              libssl-dev:${{ matrix.apt-arch }} libwebkit2gtk-4.0-dev:${{ matrix.apt-arch }} \
                              jq

      - name: 🧰 Install toolchain
        if: matrix.runner == 'windows-latest'
        run: chocolatey install jq

      - name: 🧰 Install toolchain
        if: matrix.runner == 'macos-latest'
        run: brew install jq

      # Debian Bullseye distributes a too old Node.js version, so set up a more modern one externally
      - name: 🧰 Install Node.js
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: packages/packsquash_gui/package-lock.json

      - name: 📥 Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Keep the commit history for proper version information

      # Necessary due to Tauri macro expectations. See: https://github.com/tauri-apps/tauri/issues/3142
      - name: 📁 Create GUI package frontend dist directory
        run: mkdir packages/packsquash_gui/dist

      - name: 🧰 Install Linux ARM64 cross-compilation toolchain
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: apt-get install -yq gcc-aarch64-linux-gnu qemu-user

      - name: 🧰 Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ env.CARGO_BUILD_TARGET }}
          components: rust-src

      - name: 💨 Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: 🧰 Install cargo-deb
        if: matrix.runner == 'ubuntu-latest'
        uses: actions-rs/install@v0.1
        env:
          CARGO_BUILD_TARGET: ${{ matrix.host-target }}
        with:
          crate: cargo-deb
          version: 1.41.0

      - name: 🧰 Install tauri-cli
        if: matrix.runner != 'ubuntu-latest'
        uses: actions-rs/install@v0.1
        env:
          CARGO_BUILD_TARGET: ${{ matrix.host-target }}
        with:
          crate: tauri-cli

      # Our build container is minimal, and it doesn't contain any systemd package.
      # systemd is responsible for setting up the machine ID files we use for
      # testing the system ID retrieval code, so copy a dummy one
      - name: 📏 Set up a dummy D-Bus machine ID for tests
        if: matrix.runner == 'ubuntu-latest'
        run: cat /proc/sys/kernel/random/boot_id | tr -d '-' > /run/machine-id

      - name: ✔️ Run tests
        if: matrix.target != 'aarch64-apple-darwin'
        run: cargo test --release -- -Z unstable-options --report-time

      - name: 🔨 Build with optimized standard library
        run: cargo build --target ${{ env.CARGO_BUILD_TARGET }} -Z build-std --release

      - name: 🔨 Build GUI frontend
        working-directory: packages/packsquash_gui
        run: |
          npm ci
          npm run build

      - name: 🔨 Generate CLI Debian package
        if: matrix.runner == 'ubuntu-latest'
        run: packages/packsquash_cli/bundles/deb/build.sh --target ${{ env.CARGO_BUILD_TARGET }} -- -Z build-std

      - name: 🔨 Generate CLI AppImage
        if: matrix.runner == 'ubuntu-latest'
        run: packages/packsquash_cli/bundles/appimage/build.sh

      - name: 🔨 Generate GUI Debian package
        if: matrix.runner == 'ubuntu-latest'
        run: packages/packsquash_gui/src-tauri/bundles/deb/build.sh --target ${{ env.CARGO_BUILD_TARGET }} -- -Z build-std

      - name: 🔨 Generate GUI AppImage
        if: matrix.runner == 'ubuntu-latest'
        run: packages/packsquash_gui/src-tauri/bundles/appimage/build.sh

      - name: 🔨 Generate GUI MSIs, dmg and update artifacts
        if: matrix.runner != 'ubuntu-latest'
        run: cargo tauri build -v --target ${{ matrix.target }}

      - name: 🔨 Generate GUI multilingual MSI installer
        if: matrix.runner == 'windows-latest'
        run: packages/packsquash_gui/src-tauri/bundles/wix/build_multilingual_installer.ps1

      - name: 📤 Upload CLI binary
        if: matrix.runner != 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: PackSquash CLI executable (${{ matrix.target }})
          path: target/${{ env.CARGO_BUILD_TARGET }}/release/${{ matrix.cli-executable }}

      - name: 📤 Upload CLI Debian package
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: PackSquash CLI Debian package (${{ matrix.apt-arch }})
          path: target/${{ env.CARGO_BUILD_TARGET }}/debian/packsquash_*.deb

      - name: 📤 Upload CLI AppImage
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: PackSquash CLI AppImage (${{ matrix.appimage-arch }})
          path: target/appimage/PackSquash-*-${{ matrix.appimage-arch }}.AppImage

      - name: 📤 Upload CLI AppImage update diff
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: PackSquash CLI AppImage zsync (${{ matrix.appimage-arch }})
          path: target/appimage/PackSquash-*-${{ matrix.appimage-arch }}.AppImage.zsync

      - name: 📤 Upload GUI Debian package
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: PackSquash GUI Debian package (${{ matrix.apt-arch }})
          path: target/${{ env.CARGO_BUILD_TARGET }}/debian/packsquash-gui_*.deb

      - name: 📤 Upload GUI AppImage
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: PackSquash GUI AppImage (${{ matrix.appimage-arch }})
          path: target/appimage/PackSquash (GUI)-*-${{ matrix.appimage-arch }}.AppImage

      - name: 📤 Upload GUI AppImage update diff
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: PackSquash GUI AppImage zsync (${{ matrix.appimage-arch }})
          path: target/appimage/PackSquash (GUI)-*-${{ matrix.appimage-arch }}.AppImage.zsync

  build-universal-macos-binaries:

    runs-on: macos-latest

    needs: build

    steps:
      - name: 📥 Download PackSquash CLI x64 MacOS executable
        uses: actions/download-artifact@v3
        with:
          name: PackSquash CLI executable (x86_64-apple-darwin)
          path: packsquash-x64

      - name: 📥 Download PackSquash CLI ARM64 MacOS executable
        uses: actions/download-artifact@v3
        with:
          name: PackSquash CLI executable (aarch64-apple-darwin)
          path: packsquash-aarch64

      - name: 🔨 Generate universal CLI binary
        run: lipo -create -output packsquash_cli packsquash-x64/packsquash_cli packsquash-aarch64/packsquash_cli

      - name: 📤 Upload universal CLI binary
        uses: actions/upload-artifact@v3
        with:
          name: PackSquash CLI executable (universal-apple-darwin)
          path: packsquash_cli

  build-docker-images:

    runs-on: ubuntu-latest

    env:
      # Defaults to docker.io (Docker Hub)
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}

    needs: build

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@v3

      - name: 🧰 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ⚙️ Generate Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Tag the image as "edge" for every commit on master.
          # Maintain the "latest", full and major and minor semver tags for each semver tag push
          tags: |
            type=edge,branch=master
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.description=Docker image for PackSquash, the Minecraft resource and data pack optimizer.

      - name: 📥 Download PackSquash x64 AppImage
        uses: actions/download-artifact@v3
        with:
          name: PackSquash CLI AppImage (x86_64)

      # Docker uses different architecture names
      - name: 📁 Rename PackSquash x64 AppImage
        run: mv PackSquash-*-x86_64.AppImage PackSquash-*-amd64.AppImage

      - name: 📥 Download PackSquash ARM64 AppImage
        uses: actions/download-artifact@v3
        with:
          name: PackSquash CLI AppImage (aarch64)

      - name: 📁 Rename PackSquash ARM64 AppImage
        run: mv PackSquash-*-aarch64.AppImage PackSquash-*-arm64.AppImage

      - name: 🔍 Check workflow package write permission
        id: check_write_permission
        uses: scherermichael-oss/action-has-permission@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # The GitHub token needs the package:write permission for the push to work.
      # This permission is not given to PRs from forked repositories.
      # See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      - name: ⚙️ Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        if: steps.check_write_permission.outputs.has-permission
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔨 Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ steps.check_write_permission.outputs.has-permission == '1' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
