name: Rust CI

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install latest Rust nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-pc-windows-gnu
        override: true
        components: rustfmt, clippy, rust-src

    - name: Install GStreamer build dependencies
      run: sudo apt-get update && sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

    - name: Install cross-compilation toolchains
      run: sudo apt-get install gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 mingw-w64-tools

    - name: Clippy check
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D warnings

    #- name: Release Linux build
    #  uses: actions-rs/cargo@v1
    #  with:
    #    command: build
    #    args: --release --target x86_64-unknown-linux-gnu -Z build-std

    - name: Release Windows build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target x86_64-pc-windows-gnu -Z build-std

    - name: Strip symbols from Linux binary
      run: strip target/x86_64-unknown-linux-gnu/release/packsquash

    - name: Upload Linux binary
      uses: actions/upload-artifact@v2
      with:
        name: 'PackSquash executable (Linux)'
        path: target/x86_64-unknown-linux-gnu/release/packsquash

    #- name: Upload Windows binary
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: 'PackSquash executable (Windows)'
    #    path: target/x86_64-pc-windows-gnu/release/packsquash.exe
