name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install latest Rust stable toolchain (Unix)
      if: runner.os != 'Windows'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Install MSYS2 (Windows)
      if: runner.os == 'Windows'
      run: choco install msys2

    - name: Install GStreamer build and runtime dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good

    - name: Install GStreamer build and runtime dependencies (Windows)
      if: runner.os == 'Windows'
      run: C:\tools\msys64\usr\bin\env MSYSTEM=MINGW64 C:\tools\msys64\usr\bin\bash -l -c "pacman -S mingw-w64-x86_64-rust pkg-config mingw-w64-x86_64-gstreamer mingw-w64-x86_64-gst-plugins-base mingw-w64-x86_64-gst-plugins-good"

    - name: Install GStreamer build and runtime dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install gstreamer gst-plugins-base gst-plugins-good

    - name: Clippy check (Linux)
      if: runner.os == 'Linux'
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D warnings -A clippy::unreadable_literal 

    - name: Release build (Unix)
      if: runner.os != 'Windows'
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Release build (Windows)
      if: runner.os == 'Windows'
      run: C:\tools\msys64\usr\bin\env MSYSTEM=MINGW64 C:\tools\msys64\usr\bin\bash -l -c "cargo build --release"

    - name: Strip debugging symbols from binary (Unix)
      if: runner.os != 'Windows'
      run: strip target/release/packsquash

    - name: Upload executable artifact (Unix)
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: 'PackSquash executable'
        path: target/release/packsquash

    - name: Upload executable artifact (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: 'PackSquash executable'
        path: target/release/packsquash.exe
